export const PREDEFINED_NETWORKS = [
  // Code & Developer Platforms
  { id: 'github', name: 'GitHub', category: 'Code', icon: 'Github', color: 'bg-slate-900 text-white dark:bg-slate-800', baseUrl: 'https://github.com/' },
  { id: 'gitlab', name: 'GitLab', category: 'Code', icon: 'Code', color: 'bg-orange-600 text-white', baseUrl: 'https://gitlab.com/' },
  { id: 'bitbucket', name: 'Bitbucket', category: 'Code', icon: 'Code', color: 'bg-blue-600 text-white', baseUrl: 'https://bitbucket.org/' },
  { id: 'stackoverflow', name: 'Stack Overflow', category: 'Code', icon: 'Code', color: 'bg-amber-600 text-white', baseUrl: 'https://stackoverflow.com/users/' },
  { id: 'codepen', name: 'CodePen', category: 'Code', icon: 'Code', color: 'bg-slate-800 text-white', baseUrl: 'https://codepen.io/' },
  { id: 'replit', name: 'Replit', category: 'Code', icon: 'Code', color: 'bg-red-600 text-white', baseUrl: 'https://replit.com/@' },
  { id: 'leetcode', name: 'LeetCode', category: 'Code', icon: 'Code', color: 'bg-yellow-600 text-white', baseUrl: 'https://leetcode.com/' },
  { id: 'kaggle', name: 'Kaggle', category: 'Code', icon: 'Code', color: 'bg-sky-600 text-white', baseUrl: 'https://kaggle.com/' },
  { id: 'devto', name: 'Dev.to', category: 'Code', icon: 'BookOpen', color: 'bg-slate-900 text-white', baseUrl: 'https://dev.to/' },
  { id: 'hashnode', name: 'Hashnode', category: 'Code', icon: 'BookOpen', color: 'bg-blue-600 text-white', baseUrl: 'https://hashnode.com/@' },
  { id: 'hackernews', name: 'HackerNews', category: 'Code', icon: 'Code', color: 'bg-amber-700 text-white', baseUrl: 'https://news.ycombinator.com/user?id=' },
  { id: 'sourceforge', name: 'SourceForge', category: 'Code', icon: 'Code', color: 'bg-orange-500 text-white', baseUrl: 'https://sourceforge.net/u/' },
  { id: 'npm', name: 'npm', category: 'Code', icon: 'Code', color: 'bg-red-700 text-white', baseUrl: 'https://npmjs.com/~' },
  { id: 'pypi', name: 'PyPI Python', category: 'Code', icon: 'Code', color: 'bg-blue-700 text-white', baseUrl: 'https://pypi.org/user/' },
  { id: 'docker', name: 'Docker Hub', category: 'Code', icon: 'Code', color: 'bg-sky-500 text-white', baseUrl: 'https://hub.docker.com/u/' },
  { id: 'producthunt', name: 'Product Hunt', category: 'Code', icon: 'Globe', color: 'bg-orange-600 text-white', baseUrl: 'https://producthunt.com/@' },
  { id: 'glitch', name: 'Glitch', category: 'Code', icon: 'Code', color: 'bg-indigo-500 text-white', baseUrl: 'https://glitch.com/@' },
  { id: 'codeberg', name: 'Codeberg', category: 'Code', icon: 'Code', color: 'bg-sky-700 text-white', baseUrl: 'https://codeberg.org/' },
  { id: 'huggingface', name: 'Hugging Face AI', category: 'Code', icon: 'Code', color: 'bg-amber-500 text-white', baseUrl: 'https://huggingface.co/' },
  { id: 'gist', name: 'GitHub Gist', category: 'Code', icon: 'Github', color: 'bg-slate-800 text-white', baseUrl: 'https://gist.github.com/' },
  { id: 'exercism', name: 'Exercism', category: 'Code', icon: 'Code', color: 'bg-purple-700 text-white', baseUrl: 'https://exercism.org/profiles/' },
  { id: 'codecademy', name: 'Codecademy', category: 'Code', icon: 'Code', color: 'bg-indigo-700 text-white', baseUrl: 'https://codecademy.com/profiles/' },
  { id: 'freecodecamp', name: 'freeCodeCamp', category: 'Code', icon: 'Code', color: 'bg-emerald-800 text-white', baseUrl: 'https://freecodecamp.org/' },
  { id: 'codewars', name: 'Codewars', category: 'Code', icon: 'Code', color: 'bg-rose-800 text-white', baseUrl: 'https://codewars.com/users/' },
  { id: 'stackblitz', name: 'StackBlitz', category: 'Code', icon: 'Code', color: 'bg-blue-500 text-white', baseUrl: 'https://stackblitz.com/@' },

  // Professional & Freelance Platforms
  { id: 'linkedin', name: 'LinkedIn', category: 'Professional', icon: 'Linkedin', color: 'bg-blue-600 text-white', baseUrl: 'https://linkedin.com/in/' },
  { id: 'upwork', name: 'Upwork', category: 'Freelance', icon: 'Globe', color: 'bg-emerald-600 text-white', baseUrl: 'https://upwork.com/freelancers/~' },
  { id: 'fiverr', name: 'Fiverr', category: 'Freelance', icon: 'Globe', color: 'bg-emerald-500 text-white', baseUrl: 'https://fiverr.com/' },
  { id: 'freelancer', name: 'Freelancer', category: 'Freelance', icon: 'Globe', color: 'bg-sky-600 text-white', baseUrl: 'https://freelancer.com/u/' },
  { id: 'toptal', name: 'Toptal', category: 'Freelance', icon: 'Globe', color: 'bg-blue-800 text-white', baseUrl: 'https://toptal.com/resume/' },
  { id: 'wellfound', name: 'Wellfound (AngelList)', category: 'Professional', icon: 'Globe', color: 'bg-slate-900 text-white', baseUrl: 'https://wellfound.com/u/' },
  { id: 'polywork', name: 'Polywork', category: 'Professional', icon: 'Globe', color: 'bg-indigo-600 text-white', baseUrl: 'https://polywork.com/' },
  { id: 'contra', name: 'Contra', category: 'Freelance', icon: 'Globe', color: 'bg-slate-900 text-white', baseUrl: 'https://contra.com/' },
  { id: 'guru', name: 'Guru', category: 'Freelance', icon: 'Globe', color: 'bg-blue-700 text-white', baseUrl: 'https://guru.com/freelancers/' },
  { id: 'peopleperhour', name: 'PeoplePerHour', category: 'Freelance', icon: 'Globe', color: 'bg-amber-600 text-white', baseUrl: 'https://peopleperhour.com/freelancer/' },
  { id: 'malt', name: 'Malt', category: 'Freelance', icon: 'Globe', color: 'bg-rose-600 text-white', baseUrl: 'https://malt.com/profile/' },
  { id: 'readcv', name: 'ReadCV', category: 'Professional', icon: 'BookOpen', color: 'bg-slate-800 text-white', baseUrl: 'https://read.cv/' },
  { id: 'peerlist', name: 'Peerlist', category: 'Professional', icon: 'Globe', color: 'bg-emerald-700 text-white', baseUrl: 'https://peerlist.io/' },
  { id: 'aboutme', name: 'About.me', category: 'Professional', icon: 'Globe', color: 'bg-blue-500 text-white', baseUrl: 'https://about.me/' },
  { id: 'crunchbase', name: 'Crunchbase', category: 'Professional', icon: 'Globe', color: 'bg-blue-900 text-white', baseUrl: 'https://crunchbase.com/person/' },

  // Design & Creative
  { id: 'figma', name: 'Figma Community', category: 'Design', icon: 'Globe', color: 'bg-purple-600 text-white', baseUrl: 'https://figma.com/@' },
  { id: 'behance', name: 'Behance', category: 'Design', icon: 'Globe', color: 'bg-blue-700 text-white', baseUrl: 'https://behance.net/' },
  { id: 'dribbble', name: 'Dribbble', category: 'Design', icon: 'Dribbble', color: 'bg-pink-500 text-white', baseUrl: 'https://dribbble.com/' },
  { id: 'artstation', name: 'ArtStation', category: 'Design', icon: 'Globe', color: 'bg-sky-600 text-white', baseUrl: 'https://artstation.com/' },
  { id: 'deviantart', name: 'DeviantArt', category: 'Design', icon: 'Globe', color: 'bg-emerald-600 text-white', baseUrl: 'https://deviantart.com/' },
  { id: 'unsplash', name: 'Unsplash', category: 'Media', icon: 'Globe', color: 'bg-slate-900 text-white', baseUrl: 'https://unsplash.com/@' },
  { id: 'flickr', name: 'Flickr', category: 'Media', icon: 'Globe', color: 'bg-pink-600 text-white', baseUrl: 'https://flickr.com/photos/' },
  { id: '500px', name: '500px', category: 'Media', icon: 'Globe', color: 'bg-slate-800 text-white', baseUrl: 'https://500px.com/p/' },
  { id: 'vsco', name: 'VSCO', category: 'Media', icon: 'Globe', color: 'bg-slate-900 text-white', baseUrl: 'https://vsco.co/' },
  { id: 'giphy', name: 'Giphy', category: 'Media', icon: 'Globe', color: 'bg-emerald-500 text-white', baseUrl: 'https://giphy.com/channel/' },

  // Social & Community Networks
  { id: 'twitter', name: 'Twitter / X', category: 'Social', icon: 'Twitter', color: 'bg-black text-white dark:bg-slate-900', baseUrl: 'https://x.com/' },
  { id: 'facebook', name: 'Facebook', category: 'Social', icon: 'Facebook', color: 'bg-blue-700 text-white', baseUrl: 'https://facebook.com/' },
  { id: 'instagram', name: 'Instagram', category: 'Social', icon: 'Instagram', color: 'bg-pink-600 text-white', baseUrl: 'https://instagram.com/' },
  { id: 'threads', name: 'Threads', category: 'Social', icon: 'Twitter', color: 'bg-black text-white', baseUrl: 'https://threads.net/@' },
  { id: 'reddit', name: 'Reddit', category: 'Social', icon: 'MessageSquare', color: 'bg-orange-600 text-white', baseUrl: 'https://reddit.com/user/' },
  { id: 'pinterest', name: 'Pinterest', category: 'Social', icon: 'Globe', color: 'bg-red-600 text-white', baseUrl: 'https://pinterest.com/' },
  { id: 'tumblr', name: 'Tumblr', category: 'Social', icon: 'Globe', color: 'bg-blue-900 text-white', baseUrl: 'https://tumblr.com/' },
  { id: 'quora', name: 'Quora', category: 'Social', icon: 'Globe', color: 'bg-red-700 text-white', baseUrl: 'https://quora.com/profile/' },
  { id: 'mastodon', name: 'Mastodon', category: 'Social', icon: 'Globe', color: 'bg-indigo-600 text-white', baseUrl: 'https://mastodon.social/@' },
  { id: 'bluesky', name: 'Bluesky', category: 'Social', icon: 'Globe', color: 'bg-sky-500 text-white', baseUrl: 'https://bsky.app/profile/' },
  { id: 'lemon8', name: 'Lemon8', category: 'Social', icon: 'Globe', color: 'bg-yellow-500 text-white', baseUrl: 'https://lemon8-app.com/' },
  { id: 'nextdoor', name: 'Nextdoor', category: 'Social', icon: 'Globe', color: 'bg-emerald-600 text-white', baseUrl: 'https://nextdoor.com/profile/' },
  { id: 'letterboxd', name: 'Letterboxd', category: 'Social', icon: 'Globe', color: 'bg-emerald-600 text-white', baseUrl: 'https://letterboxd.com/' },
  { id: 'goodreads', name: 'Goodreads', category: 'Social', icon: 'BookOpen', color: 'bg-amber-800 text-white', baseUrl: 'https://goodreads.com/' },
  { id: 'clubhouse', name: 'Clubhouse', category: 'Social', icon: 'Globe', color: 'bg-amber-600 text-white', baseUrl: 'https://clubhouse.com/@' },
  { id: 'meetup', name: 'Meetup', category: 'Social', icon: 'Globe', color: 'bg-rose-600 text-white', baseUrl: 'https://meetup.com/members/' },
  { id: 'bereal', name: 'BeReal', category: 'Social', icon: 'Globe', color: 'bg-black text-white', baseUrl: 'https://bereal.com/' },
  { id: 'snapchat', name: 'Snapchat', category: 'Social', icon: 'Globe', color: 'bg-yellow-400 text-slate-900', baseUrl: 'https://snapchat.com/add/' },
  { id: 'vkontakte', name: 'VKontakte (VK)', category: 'Social', icon: 'Globe', color: 'bg-blue-600 text-white', baseUrl: 'https://vk.com/' },
  { id: 'weibo', name: 'Sina Weibo', category: 'Social', icon: 'Globe', color: 'bg-red-600 text-white', baseUrl: 'https://weibo.com/' },
  { id: 'keybase', name: 'Keybase', category: 'Social', icon: 'Globe', color: 'bg-amber-500 text-white', baseUrl: 'https://keybase.io/' },
  { id: 'truthsocial', name: 'Truth Social', category: 'Social', icon: 'Globe', color: 'bg-blue-800 text-white', baseUrl: 'https://truthsocial.com/@' },

  // Video & Streaming Media
  { id: 'youtube', name: 'YouTube', category: 'Media', icon: 'Youtube', color: 'bg-red-600 text-white', baseUrl: 'https://youtube.com/@' },
  { id: 'tiktok', name: 'TikTok', category: 'Media', icon: 'Globe', color: 'bg-black text-white', baseUrl: 'https://tiktok.com/@' },
  { id: 'twitch', name: 'Twitch', category: 'Media', icon: 'Globe', color: 'bg-purple-600 text-white', baseUrl: 'https://twitch.tv/' },
  { id: 'vimeo', name: 'Vimeo', category: 'Media', icon: 'Globe', color: 'bg-sky-500 text-white', baseUrl: 'https://vimeo.com/' },
  { id: 'dailymotion', name: 'Dailymotion', category: 'Media', icon: 'Globe', color: 'bg-slate-800 text-white', baseUrl: 'https://dailymotion.com/' },
  { id: 'rumble', name: 'Rumble', category: 'Media', icon: 'Globe', color: 'bg-emerald-600 text-white', baseUrl: 'https://rumble.com/c/' },
  { id: 'kick', name: 'Kick Streaming', category: 'Media', icon: 'Globe', color: 'bg-emerald-500 text-slate-950 font-bold', baseUrl: 'https://kick.com/' },
  { id: 'odysee', name: 'Odysee', category: 'Media', icon: 'Globe', color: 'bg-rose-500 text-white', baseUrl: 'https://odysee.com/@' },
  { id: 'bilibili', name: 'Bilibili', category: 'Media', icon: 'Globe', color: 'bg-sky-400 text-white', baseUrl: 'https://space.bilibili.com/' },

  // Audio & Podcasts
  { id: 'spotify', name: 'Spotify', category: 'Media', icon: 'Music', color: 'bg-emerald-500 text-white', baseUrl: 'https://spotify.com/' },
  { id: 'soundcloud', name: 'SoundCloud', category: 'Media', icon: 'Music', color: 'bg-orange-600 text-white', baseUrl: 'https://soundcloud.com/' },
  { id: 'applemusic', name: 'Apple Music', category: 'Media', icon: 'Music', color: 'bg-rose-600 text-white', baseUrl: 'https://music.apple.com/profile/' },
  { id: 'bandcamp', name: 'Bandcamp', category: 'Media', icon: 'Music', color: 'bg-sky-600 text-white', baseUrl: 'https://bandcamp.com/' },
  { id: 'tidal', name: 'Tidal Music', category: 'Media', icon: 'Music', color: 'bg-black text-white', baseUrl: 'https://tidal.com/' },
  { id: 'deezer', name: 'Deezer', category: 'Media', icon: 'Music', color: 'bg-purple-700 text-white', baseUrl: 'https://deezer.com/us/profile/' },
  { id: 'lastfm', name: 'Last.fm', category: 'Media', icon: 'Music', color: 'bg-red-700 text-white', baseUrl: 'https://last.fm/user/' },
  { id: 'mixcloud', name: 'Mixcloud', category: 'Media', icon: 'Music', color: 'bg-indigo-700 text-white', baseUrl: 'https://mixcloud.com/' },
  { id: 'audiomack', name: 'Audiomack', category: 'Media', icon: 'Music', color: 'bg-amber-500 text-slate-900', baseUrl: 'https://audiomack.com/' },
  { id: 'applepodcasts', name: 'Apple Podcasts', category: 'Media', icon: 'Music', color: 'bg-purple-800 text-white', baseUrl: 'https://podcasts.apple.com/' },

  // Gaming Platforms
  { id: 'discord', name: 'Discord', category: 'Gaming', icon: 'MessageSquare', color: 'bg-indigo-600 text-white', baseUrl: 'https://discord.gg/' },
  { id: 'steam', name: 'Steam Community', category: 'Gaming', icon: 'Globe', color: 'bg-slate-900 text-white', baseUrl: 'https://steamcommunity.com/id/' },
  { id: 'roblox', name: 'Roblox', category: 'Gaming', icon: 'Globe', color: 'bg-slate-800 text-white', baseUrl: 'https://roblox.com/users/' },
  { id: 'epicgames', name: 'Epic Games', category: 'Gaming', icon: 'Globe', color: 'bg-slate-900 text-white', baseUrl: 'https://epicgames.com/id/' },
  { id: 'xbox', name: 'Xbox Live', category: 'Gaming', icon: 'Globe', color: 'bg-emerald-600 text-white', baseUrl: 'https://xbox.com/profile/' },
  { id: 'playstation', name: 'PlayStation Network', category: 'Gaming', icon: 'Globe', color: 'bg-blue-700 text-white', baseUrl: 'https://playstation.com/' },
  { id: 'nintendo', name: 'Nintendo Switch', category: 'Gaming', icon: 'Globe', color: 'bg-red-600 text-white', baseUrl: 'https://nintendo.com/' },
  { id: 'itchio', name: 'itch.io Games', category: 'Gaming', icon: 'Globe', color: 'bg-rose-600 text-white', baseUrl: 'https://itch.io/' },
  { id: 'chesscom', name: 'Chess.com', category: 'Gaming', icon: 'Globe', color: 'bg-emerald-700 text-white', baseUrl: 'https://chess.com/member/' },
  { id: 'lichess', name: 'Lichess Org', category: 'Gaming', icon: 'Globe', color: 'bg-slate-800 text-white', baseUrl: 'https://lichess.org/@/' },
  { id: 'speedrun', name: 'Speedrun.com', category: 'Gaming', icon: 'Globe', color: 'bg-indigo-700 text-white', baseUrl: 'https://speedrun.com/user/' },

  // Direct Contact & Messaging
  { id: 'whatsapp', name: 'WhatsApp', category: 'Contact', icon: 'PhoneCall', color: 'bg-emerald-600 text-white', baseUrl: 'https://wa.me/' },
  { id: 'telegram', name: 'Telegram', category: 'Contact', icon: 'Send', color: 'bg-sky-500 text-white', baseUrl: 'https://t.me/' },
  { id: 'signal', name: 'Signal Messenger', category: 'Contact', icon: 'PhoneCall', color: 'bg-blue-600 text-white', baseUrl: 'https://signal.me/#p/' },
  { id: 'wechat', name: 'WeChat', category: 'Contact', icon: 'PhoneCall', color: 'bg-emerald-600 text-white', baseUrl: 'https://wechat.com/' },
  { id: 'skype', name: 'Skype', category: 'Contact', icon: 'PhoneCall', color: 'bg-sky-600 text-white', baseUrl: 'https://skype.com/' },
  { id: 'viber', name: 'Viber', category: 'Contact', icon: 'PhoneCall', color: 'bg-purple-600 text-white', baseUrl: 'https://viber.com/' },
  { id: 'line', name: 'LINE App', category: 'Contact', icon: 'PhoneCall', color: 'bg-emerald-500 text-white', baseUrl: 'https://line.me/ti/p/' },
  { id: 'kakaotalk', name: 'KakaoTalk', category: 'Contact', icon: 'PhoneCall', color: 'bg-yellow-400 text-slate-900', baseUrl: 'https://kakaotalk.com/' },
  { id: 'messenger', name: 'Facebook Messenger', category: 'Contact', icon: 'Send', color: 'bg-blue-600 text-white', baseUrl: 'https://m.me/' },
  { id: 'email', name: 'Email Address', category: 'Contact', icon: 'Send', color: 'bg-indigo-600 text-white', baseUrl: 'mailto:' },
  { id: 'phone', name: 'Direct Phone', category: 'Contact', icon: 'PhoneCall', color: 'bg-slate-800 text-white', baseUrl: 'tel:' },

  // Crypto & Web3
  { id: 'opensea', name: 'OpenSea NFT', category: 'Crypto', icon: 'Globe', color: 'bg-blue-600 text-white', baseUrl: 'https://opensea.io/' },
  { id: 'rarible', name: 'Rarible', category: 'Crypto', icon: 'Globe', color: 'bg-amber-500 text-slate-900', baseUrl: 'https://rarible.com/' },
  { id: 'foundation', name: 'Foundation App', category: 'Crypto', icon: 'Globe', color: 'bg-black text-white', baseUrl: 'https://foundation.app/@' },
  { id: 'farcaster', name: 'Warpcast / Farcaster', category: 'Crypto', icon: 'Globe', color: 'bg-purple-700 text-white', baseUrl: 'https://warpcast.com/' },
  { id: 'lens', name: 'Lens Protocol / Hey', category: 'Crypto', icon: 'Globe', color: 'bg-emerald-600 text-white', baseUrl: 'https://hey.xyz/u/' },
  { id: 'mirror', name: 'Mirror.xyz', category: 'Crypto', icon: 'BookOpen', color: 'bg-blue-500 text-white', baseUrl: 'https://mirror.xyz/' },
  { id: 'etherscan', name: 'Etherscan Wallet', category: 'Crypto', icon: 'Globe', color: 'bg-slate-800 text-white', baseUrl: 'https://etherscan.io/address/' },
  { id: 'solscan', name: 'Solscan Solana', category: 'Crypto', icon: 'Globe', color: 'bg-purple-800 text-white', baseUrl: 'https://solscan.io/account/' },
  { id: 'coinmarketcap', name: 'CoinMarketCap', category: 'Crypto', icon: 'Globe', color: 'bg-blue-700 text-white', baseUrl: 'https://coinmarketcap.com/community/profile/' },

  // Custom & Personal Website
  { id: 'website', name: 'Personal Website', category: 'Professional', icon: 'Globe', color: 'bg-indigo-600 text-white', baseUrl: 'https://' }
];
